# Generated by Django 3.0.2 on 2021-03-22 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheff',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID_Cheff')),
                ('direction', models.CharField(max_length=120, verbose_name='Direction')),
                ('curriculum', models.TextField(max_length=500, verbose_name='Curriculum Vittae')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Nome')),
                ('ingredient', models.CharField(max_length=255, unique=True, verbose_name='ingredientes')),
                ('receita', models.TextField(max_length=500, unique=True, verbose_name='Receita')),
                ('cheff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cheff', verbose_name='Cheff')),
            ],
        ),
    ]
