# Generated by Django 3.0.2 on 2021-03-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheff',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID_Cheff')),
                ('direction', models.CharField(max_length=120, verbose_name='Direction')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Receita')),
                ('type', models.CharField(choices=[('Café_da_manha', 'Café_da_manha'), ('Lanche', 'Lanche'), ('Café_da_tarde', 'Café_da_tarde'), ('Jantar', 'Jantar')], max_length=20)),
                ('thumbnail', models.ImageField(default='recipe_thumbnails/default.png', upload_to='recipe_thumbnails')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Receita')),
                ('cheff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cheff', verbose_name='Cheff')),
            ],
        ),
    ]
